Fix compilation error: Make processResponse and makeApiCall suspend functions
- Make processResponse suspend function:
  * Now calls executeToolSync which is suspend
  * All callers are already in suspend/coroutine contexts

- Make makeApiCall suspend function:
  * Calls processResponse which is now suspend
  * Already called from withContext(Dispatchers.IO) blocks

- Make makeApiCallSimple suspend function:
  * Calls makeApiCall which is now suspend
  * Already called from withContext(Dispatchers.IO) blocks

Fixes:
- Compilation error: Suspend function should be called only from coroutine
- All functions in the call chain are now properly suspend
- Maintains compatibility with existing coroutine contexts